# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/
# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
#service: smart-recycling-backend
service: test-file-import

# The `provider` block defines where your service will be deployed
custom:
#  projectBucket: smart-recycling-backend
  projectBucket: test-file-import
  dataBucket: smart-recycling-bin-images

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
#  stackName: smart-recycling-backend
  stackName: test-file-import
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "rekognition:*"
      Resource: "*"

# The `functions` block defines what code to deploy
functions:

  uploadFile:
    handler: fileUploaderHome.handler
    environment:
      Bucket: ${self:custom.dataBucket}/upload
    events:
      - http:
          path: /upload
          method: post
          cors: true

  healthCheck:
    handler: healthCheckHome.handler
    events:
      - http:
          path: /healthCheck
          method: get

  getAllFiles:
    handler: getAllFilesHome.handler
    environment:
      BUCKET: ${self:custom.dataBucket}
    events:
      - http:
          path: /getAllFiles
          method: get

  detectLabel:
    handler: detectLabelHome.handler
    environment:
      BUCKET: ${self:custom.dataBucket}
    events:
      - http:
          path: /detectLabel
          method: post
